name: Build API Docs

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  call-doc-build-workflow:
    uses: clojure/build.ci/.github/workflows/doc-build.yml@master
    with:
      project: clojure/core.async
